server:
  port: 8080
#spring:
   #profiles:
     # active: docker,local
      #active: docker,local
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: outbox-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      #value-deserializer-target-type:
      properties: 
          spring:
            json:
              trusted:
                packages: '*'
            deserializer-key-delegate-class: com.poc.cdc.infratructure.consumers.model.Event
        