version: '3'

services:
     
  postgress-nosql-service:
    build: .
    image: com.poc.cdc/postgressnosql:0.0.1-SNAPSHOT
    environment:
      SPRING_PROFILES_ACTIVE: "docker" 
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-db:5432/orderdb?currentSchema=inventory
    ports:
      - "8081:8081"
    depends_on:
      - destino-db
  destino-db:
    image: quay.io/debezium/example-postgres:2.1.1.Final
    ports:
     - 5433:5433
    healthcheck:
      test: "pg_isready -U postgresuser -d orderdb"
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=orderdb
 ##########################################################################     
 #pgadmin service
 ##########################################################################  
  pgadmin4_2:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "Jcallejo2023"
    ports:
      - 82:82
    depends_on:
      - destino-db     