version: '3.8'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:3.0.8.Final
    #image: quay.io/debezium/zookeeper:1.9
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: quay.io/debezium/kafka:3.0.8.Final
    #image: quay.io/debezium/kafka:1.9
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=LISTENER_SEVICE://:9092,LISTENER_KAFDROP://kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_SEVICE://localhost:9092,LISTENER_KAFDROP://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP= LISTENER_SEVICE:PLAINTEXT, LISTENER_KAFDROP:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME= LISTENER_SEVICE
    depends_on:
      - zookeeper

  connect:
    image: quay.io/debezium/connect:3.0.8.Final
    #image: quay.io/debezium/connect:1.9
    container_name: connect
    ports:
      - 8083:8083
    volumes:
        #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
        - ./kafka/ojdbc8.jar:/kafka/libs/ojdbc8.jar
        - ./kafka/ojdbc11.jar:/kafka/libs/ojdbc11.jar
        - ./kafka/ojdbc17.jar:/kafka/libs/ojdbc17.jar

        # - ./../kafka/ojdbc8.jar:/kafka/libs/ojdbc8.jar
    environment:
      - BOOTSTRAP_SERVERS=kafka:29092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - zookeeper
      - kafka
      - dbz_oracle21
      
  replicator_oracle:
    #image: com.poc.cdc/replicator-mongodb:0.0.1-SNAPSHOT
    build:
        dockerfile: Dockerfile
        context: ./../../
    container_name: replicator_oracle
    environment:
      - SPRING_DATA_MONGODB_USERNAME=admin
      - SPRING_DATA_MONGODB_PASSWORD=admin1
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_DATABASE=inventory
      - SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE=admin
      - KAFKA_HOST=kafka:9092
      - KAFKA_GROUP=replicator-dev
      - KAFKA_TOPIC_PRODUCT=server1.C__DBZUSER.PRODUCTS
      - KAFKA_TOPIC_CUSTOMER=server1.C__DBZUSER.CUSTOMERS
      - KAFKA_TOPIC_ORDERS=server1.C__DBZUSER.ORDERS
    depends_on:
      - kafka
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin1      
  dbz_oracle21:
    #image: container-registry.oracle.com/database/enterprise:latest
    image: container-registry.oracle.com/database/enterprise:21.3.0.0
    #image: oracle21configured:v1
    container_name: dbz_oracle21
    ports:
      - 1521:1521
    volumes:
      #allow *.sql, *.sql.gz, or *.sh and is execute only if data directory is empty
      #- ./dbfiles:/docker-entrypoint-initdb.d
      #- ./dbfiles/setup:/opt/oracle/scripts/setup
      - ./../../../oracle_data_cdb:/opt/oracle/oradata
    environment:
    #Sid database
    - ORACLE_SID=ORCLCDB
    #optional this is default user 
    - ORACLE_PDB=ORCLPDB1
    # optional change user SYSTEM password 
    - ORACLE_PWD=oraclepw 
 ##########################################################################     
 #web UI for monitoring Apache Kafka clusters
 ##########################################################################       
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:29092
    depends_on:
      - zookeeper
      - kafka
 ##########################################################################     
 #dbeaver service
 ##########################################################################       
  dbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    ports:
      - 8978:8978        
    volumes: 
      - ./../../../cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - dbz_oracle21

volumes:
    cloudbeaver_data:
      driver: local    
    oracle_data_cdb:
      driver: local