spring:
   datasource:
      url: jdbc:h2:mem:test_db;MODE=PostgreSQL
      driverClassName: org.h2.Driver
      username: sa
      password: password
   sql:
    init:
      mode: always
      continue-on-error: true
   h2:
      console:
         enabled: true
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQL95Dialect
      #database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    path: /swagger.html # swagger custom path
    enabled: true  # Disabling the swagger-ui production enviroments always false